locale: "it-IT"
title: Davide Chen # Title of your site
url: "https://davidechen.it" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
google_analytics_key: "G-BE8T45S8HD"

# Default description in social shares for the jekyll-seo-tag gem
description: > # this means to ignore newlines until "baseurl:"
  My name is Davide Chen, born in Rome and raised in Naples. 
  I'm currently enrolled in the Bachelor Degree in Computer Science at the University of Pisa
  I love programming, travelling, photography and languages.

# Author details for the jekyll-seo-tag gem
author:
  name: Davide Chen
  email: davide.chen@outlook.it
  twitter: davide_logc # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name: Strata Reloaded Template
  links:
    - https://github.com/comfusion/strata-reloaded-jekyll-template

permalink: pretty

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-sitemap"

# Jekyll SEO Tag
webmaster_verifications:
  google: # 1234
  bing: # 1234
  alexa: # 1234
  yandex: # 1234

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Github
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
